### ISSUE TITLE
Coordinate system update

### ISSUE THREAD

**Issue by Uio96** [ivapylibs/puzzle_solver#10]
The current coordinate system used in the board/template script is from MatLab. We may change them to the OpenCV style.

**Comment by pv33** [comment]
@Uio96 
Of course, modify as works for python. Whatever is coded by me should be considered as requiring revisions to work. I am assuming that is what code is being referred to.

**Comment by Uio96** [comment]
Solved by 5b3f56c47d617ebbfd6229efb81f40e1056603a7
