### ISSUE TITLE
Update test scripts for adjacent class

### ISSUE THREAD

**Issue by Uio96** [ivapylibs/puzzle_solver#18]
- [x] The current test script uses the image of six shapes, which are not adjacent.  Need to simulate a new image with adjacent pieces. 
- [x]  Also the `testAdj` function in the `board` needs to be updated.

**Comment by Uio96** [comment]
Solved with 91b37d8

**Comment by pv33** [comment]
Remember to note that adjacency is based on a threshold.  That means it is possible to have an image of separated objects get treated as adjacent by having a slightly higher threshold for adjacency.

It also shouldn't be too hard to make a puzzle with just nine squares that have different colors and are close to each other but not touching. Makes it easy to calibrate and then to solve.

**Comment by Uio96** [comment]
> Remember to note that adjacency is based on a threshold. That means it is possible to have an image of separated objects get treated as adjacent by having a slightly higher threshold for adjacency.
> 
> It also shouldn't be too hard to make a puzzle with just nine squares that have different colors and are close to each other but not touching. Makes it easy to calibrate and then to solve.

Yep, I understand. I just thought the previous visualization was not that good so I created a new one.
