### ISSUE TITLE
Code: puzzle.solver

### ISSUE THREAD

**Issue by pv33** [ivapylibs/puzzle_solver#19]
This class does nothing too complex at the moment since most of the work was put into other classes and there are assumptions on how things operate in the _simple_ case (puzzle pieces are ordered).

Finish the code.
Write test script.
  Should build/load a simple puzzle for calibration.
  Create a copy. Move the pieces around (hard coded)
  Instantiate a solver (with built solution and mixed up version)
  Display puzzle
  wait a second.
  Loop through from 1 to puzzle length
   Generate and apply correction to a piece (basically take a turn)
   Plot the puzzle board
   Wait a second
 
Should depict a visual sequence of the puzzle being solved. Should be able to add a saveMe flag that, if set to true will save the puzzle board images to ``testing/data/TESTNAME_nXX.png``
Use them to create an animated gif that can be uploaded to this issue as evidence of completion (also commit to repository in ``testing/data``.

**Comment by pv33** [comment]
Only work on the minimal ``takeTurn`` functionality that automatically operates in the absence of a plan.

**Comment by Uio96** [comment]
<img src="https://user-images.githubusercontent.com/13082153/129486620-61684386-f8d5-483b-a6ba-45a092393f40.png" width="500" />
<img src="https://user-images.githubusercontent.com/13082153/129486617-2e2197e7-4573-480a-8b23-61baa72f278c.gif" width="500" />

**Comment by Uio96** [comment]
Currently, for the simple class, I do not assume that the `match` variable is naturally correct following the index of the solution board. Instead, I create a manager instance to associate the puzzle pieces between the measured board and the solution board, then assign the values to the `match` variable. 

I think this process is better in a more realistic scenario. 

See https://github.com/ivapylibs/puzzle_solver/blob/master/puzzle/solver/simple.py#L52-L60

**Comment by pv33** [comment]
@Uio96 
But, the manager class needs to know the right associations. That means you either went with enumeration as the candidate association for now, or you did some kind of "feature matching." Please clarify what was done here. Your message was not informative enough to establish how the association was established. 

Or does moments work just fine for these? That would be the missing information.

**Comment by Uio96** [comment]
> @Uio96
> But, the manager class needs to know the right associations. That means you either went with enumeration as the candidate association for now, or you did some kind of "feature matching." Please clarify what was done here. Your message was not informative enough to establish how the association was established.
> 
> Or does moments work just fine for these? That would be the missing information.

Yep. The moment feature can work on this case.

**Comment by pv33** [comment]
@Uio96 
Sorry, either that is how you programmed it, or that is not how you programmed it.  I would like to know right here, without having to look at the code, how you established the associations without relying on having ordered enumeration of pieces that already matched between the solution and the current puzzle state.

There were two paragraphs, each requiring answers.  Please answer the first paragraph.

**Comment by Uio96** [comment]
> @Uio96
> Sorry, either that is how you programmed it, or that is not how you programmed it. I would like to know right here, without having to look at the code, how you established the associations without relying on having ordered enumeration of pieces that already matched between the solution and the current puzzle state.
> 
> There were two paragraphs, each requiring answers. Please answer the first paragraph.

Sorry. My point is that the manager can use the moment feature to create the right association. The process follows your design of the member function. https://github.com/ivapylibs/puzzle_solver/blob/master/puzzle/manager.py#L117-L142

**Comment by pv33** [comment]
Thank you.  the current hard coding in the script is fine.  Eventually some of that will go into a member function when the appropriate class has been specified and ready to be coded up. Closing issue for now.
