### ISSUE TITLE
Code: puzzle.solver.twoAgent

### ISSUE THREAD

**Issue by pv33** [ivapylibs/puzzle_solver#21]
Added a two agent solver class.  

 - [x] Correct and complete the code.
 - [x] Add test script showing functionality of the two agents solving a puzzle together.

Test script should do heavy lifting for now.  As in the test script has the puzzle play loop and the display functions within it, then calls the turn taking member function of the two agent system.

I am assuming that python classes as handles by default and that updates by the agents will be recognized since they have handles to the same puzzle instances.  Please confirm this assumption for me by replying yes to the message. If not, then explain how python manages class instances and how to create a handle versus value class.

**Comment by Uio96** [comment]
> I am assuming that python classes as handles by default and that updates by the agents will be recognized since they have handles to the same puzzle instances. Please confirm this assumption for me by replying yes to the message. If not, then explain how python manages class instances and how to create a handle versus value class.

Your assumption is correct and I have finished this task.

**Comment by pv33** [comment]
@Uio96 
Missing animated video as documented evidence.

**Comment by Uio96** [comment]
<img src="https://user-images.githubusercontent.com/13082153/129486620-61684386-f8d5-483b-a6ba-45a092393f40.png" width="500" />
<img src="https://user-images.githubusercontent.com/13082153/129629878-3739d502-cc97-4e62-ab43-af8b4c8d2a7a.gif" width="500" />

Similar to https://github.com/ivapylibs/puzzle_solver/issues/19#issuecomment-899083769, but will also display the current agent status on the title.
