### ISSUE TITLE
Code: puzzle board exploded view

### ISSUE THREAD

**Issue by pv33** [ivapylibs/puzzle_solver#22]
The ``puzzle.builder.fromMask`` code stub had a member function called ``explodedPuzzle`` that did not get translated to the board.  Please implement for ``puzzle.board``

An exploded view takes a given puzzle board and "explodes" the pieces outwards so that they are no longer touching if they were before. This terminology comes from mechanical designs (see [google search: exploded view](https://www.google.com/search?q=exploded+view&client=ubuntu&hs=EBk&channel=fs&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiW2fWpka_yAhXhct8KHcPsA38Q_AUoAXoECAEQAw&biw=1200&bih=1486)). If the puzzle is gridded and the puzzle looks like the ones from ``basic07``, then an exploded view would look like that puzzle template I showed you in the last meeting (bottom row visual of this [image](https://github.com/ivapylibs/puzzle_solver/blob/master/puzzle/testing/data/puzzle_21p_fit_and_exploded_123rf.jpg)).

The function should ask for the delta x and delta y to apply to the pieces as a 2x1 array. This might make sense for the gridded puzzle only, so that might be where to put the member function.  The others probably need a different way of _exploding_ the view.  Like scaling outwards from some center point in a radial fashion.  Who knows.

Please write a test script for the exploded view. Better to prefix with ``explodeXX_TTTT`` and not ``basicXX_YY``. The prefix should be informative.

**Comment by Uio96** [comment]
![demo](https://user-images.githubusercontent.com/13082153/129493267-ea523a41-e751-46f4-a168-0b41a4fc9cdd.png)
