### ISSUE TITLE
Gridded: Solve exploded view

### ISSUE THREAD

**Issue by pv33** [ivapylibs/puzzle_solver#24]
One process that will be needed is to establish the correct locations of a puzzle from the exploded view plus a puzzle solving process. This requires going from the exploded state to the solved state one step at a time.

  1. take puzzle sketch template and create solution.
  2. explode the solution to give the current puzzle state
    - hopefully one corner piece does not change coordinates under explosion. preferably the (0,0) piece.
  3. solve each piece one at a time until the puzzle is done.
     - should be in some ordered manner. row-wise, column-wise, frontier expansion wise. pick one.

This part can be a hard coded script to do the process for now.

Later, there will be a ``plan`` generated to do the same. I will soon add an issue in another milestone for you to generate this plan and to eventually build up the ``simulator`` to parse the plan. 

Personal notes for this are in the _2021 Fall W01_ notes. First as a ``simple`` simulator then as a ``layered`` simulator that can have pieces disappear by moving to another layer temporarily.  The simulator will work with atomic actions as encoded within a ``plan`` and therefore more explicitly encode turn-based and time-based operations.  It will get us one step closer to a ROS version that does the same.

**Comment by Uio96** [comment]
<img src="https://user-images.githubusercontent.com/13082153/129998892-035e4457-9e8c-460c-8e2f-76732d1ebac6.png" width="500" />
<img src="https://user-images.githubusercontent.com/13082153/129998554-be849772-558a-46f9-82fd-a22f2c2d8f61.gif" width="500" />

**Comment by Uio96** [comment]
I double-checked my codes, and I have already used `deepcopy` before https://github.com/ivapylibs/puzzle_solver/blob/master/puzzle/builder/gridded.py#L162.

**Comment by Uio96** [comment]
![demo_simple_explod02](https://user-images.githubusercontent.com/13082153/130527111-78b53760-39a1-4ebb-890f-d71136d6cb9a.gif)

**Comment by Uio96** [comment]
Now we can work on 60 pieces with some certain image covers (The image difference needs to be distinct) by the sift feature. Our edge color feature matching cannot work very well. Usually, it would have 8-12 failure cases of the 60 matches.

![demo_simple_explode03](https://user-images.githubusercontent.com/13082153/132380214-0ec5ec8c-ea76-4854-95e0-b0ac529a01a9.gif)
