### ISSUE TITLE
connectivity classes: in/out/edge

### ISSUE THREAD

**Issue by pv33** [ivapylibs/puzzle_solver#25]
Build out puzzle piece template class to include the form of the puzzle piece in terms of whether the north, south, east, and west parts go in, out, or are flat (edge).

Presumably the puzzle piece template class has both the area data and also the boundary data. The boundary data should be parsed to establish in, out, or edge. One simple way would be to see where the convex hull center of mass is located relative to the median point of the boundary points.

**Comment by Uio96** [comment]
<img src="https://user-images.githubusercontent.com/13082153/129996796-9db8b82d-fabf-4be9-be2a-4f764ba2419a.png" width="500" />
