### ISSUE TITLE
puzzle plans

### ISSUE THREAD

**Issue by pv33** [ivapylibs/puzzle_solver#27]
Yiye and Yunzhi work to define a ``plan`` class with the proper atomic action labels. Will naturally require an _atomic action_ class.

A plan should be a list of atomic actions to apply.

Note that a board should be able to interpret and implement some actions.
I can envision a solver or something like that as able to interpret and implement some actions that the board can't, and vice versa.

**Comment by pv33** [comment]
most likely needs a ``no-op/pass/wait`` action. should have been noted in another issue I think.

**Comment by Uio96** [comment]
<img src="https://user-images.githubusercontent.com/13082153/130360696-8ab25614-8f34-4513-b0f9-ae1fd742469a.png" width="1000" />

I have corrected the basic code for `simulator` and added a test script. I have also discussed the work with Yiye @yiyeChen. He will develop a subclass of `simulator` to incorporate the human activity stuff.

**Comment by Uio96** [comment]
Yiye and I develop our plan in https://docs.google.com/document/d/1NRb9W22OnAfcKMJG04FBtlGvxFtZpH2zw0qLQuSlEqc/edit#heading=h.etfieebjk5dm
