### ISSUE TITLE
Map board :: Initial to Desired position

### ISSUE THREAD

**Issue by aevela** [ivapylibs/puzzle_solver#33]
A wrapper to call task optimizer to solve puzzles.

Requires mapping of board instance from x_o (initial x,y position) to x_d (desired x,y position) of the puzzle pieces.

**Comment by Uio96** [comment]
Dear Prof. Adan Vela,

I have added an interface for your code stuff: https://github.com/ivapylibs/puzzle_solver/blob/master/puzzle/solver/simple.py#L277-L293. See the comments for more details.

I also added a test script for you: https://github.com/ivapylibs/puzzle_solver/blob/master/puzzle/simulator/testing/60pRotateSolverNewPlan_basic.py. 

The basic idea is to simulate an exploded puzzle board then solve it according to a plan. Currently, the simulator will execute all the actions in one step. So if everything goes well, you should see an assembled board from the exploded one after the execution. The board may be with rotated pieces, where you can change the setting  https://github.com/ivapylibs/puzzle_solver/blob/master/puzzle/simulator/testing/60pRotateSolverNewPlan_basic.py#L18).

Other details: The position is defined as the top-left corner of the bounding box for a puzzle piece (after rotation correction). We follow the OpenCV's style that x represents column coordinate while y represents row coordinate.

**Comment by aevela** [comment]
Hi, do puzzle pieces have a unique id?

**Comment by Uio96** [comment]
yep

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by aevela** [comment]
Okay -- I created a small package that can be used.  It can be downloaded here: https://github.com/ADCLab/puzzleSolvers

**Comment by Uio96** [comment]
> Okay -- I created a small package that can be used. It can be downloaded here: https://github.com/ADCLab/puzzleSolvers

Dear Prof. Adan Vela, 

I have incorporated your code in my test file which I mentioned before. Here is an animation.
![60pRotateSolverNewPlan](https://user-images.githubusercontent.com/13082153/140446809-b3bfc66a-e32e-4e02-94f6-abe8976e0373.gif)

**Comment by aevela** [comment]
That is incredibly cool!  Great job.

**Comment by Uio96** [comment]
> That is incredibly cool! Great job.

Thanks, I just fixed a bug and updated the plot:
![60pRotateSolverNewPlan](https://user-images.githubusercontent.com/13082153/140449376-625b49d5-b36d-465b-a536-363349fffde5.gif)
